# Generated by Django 3.1.2 on 2020-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
