# Generated by Django 3.1.2 on 2020-11-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201101_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
    ]
