# Generated by Django 3.2.dev20200701050043 on 2020-11-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='files/'),
        ),
    ]
